export type GameKind = "slot" | "table" | "original" | "sport";

export type GameInfo = {
  slug: string;
  name: string;
  tagline: string;
  kind: GameKind;
  table?: "blackjack" | "roulette" | "baccarat";
  volatility: "Niedrig" | "Mittel" | "Hoch";
  rtp: string;
  badge?: string;
  image: string;
  featured?: boolean;
  family?: "merkur" | "pragmatic" | "studio" | "live";
};

export const GAMES: GameInfo[] = [
  {
    slug: "sport",
    name: "Wettstudio",
    tagline: "1. Liga · Live · Kombi · Cashout",
    kind: "sport",
    volatility: "Mittel",
    rtp: "94,5 %",
    badge: "Live",
    image: "/games/sport.jpg",
    featured: true,
    family: "studio",
  },
  {
    slug: "sicbo",
    name: "Sic Bo",
    tagline: "3 Würfel · Klein/Groß · Triple 180:1",
    kind: "table",
    volatility: "Hoch",
    rtp: "97,2 %",
    badge: "Live",
    image: "/games/sicbo.jpg",
    family: "live",
  },
  {
    slug: "videopoker",
    name: "Video Poker",
    tagline: "Jacks or Better · Royal 800×",
    kind: "original",
    volatility: "Mittel",
    rtp: "99,5 %",
    badge: "Klassiker",
    image: "/games/videopoker.jpg",
    family: "studio",
  },
  {
    slug: "wegeflut",
    name: "Wegeflut",
    tagline: "6 Walzen · 2–7 hoch · bis 117.649 Wege",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,2 %",
    badge: "Neu",
    image: "/games/wegeflut.jpg",
    featured: true,
    family: "pragmatic",
  },
  {
    slug: "schatzzug",
    name: "Schatzzug",
    tagline: "Hold & Collect · Sammler · 3 Nachdreher",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,1 %",
    badge: "Hot",
    image: "/games/schatzzug.jpg",
    featured: true,
    family: "studio",
  },
  {
    slug: "olymp-tor",
    name: "Olymp-Tor",
    tagline: "6×5 · 8+ überall · Orbs bis ×500",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,5 %",
    badge: "Neu",
    image: "/games/olymp-tor.jpg",
    featured: true,
    family: "pragmatic",
  },
  {
    slug: "bonbon-regen",
    name: "Bonbon-Regen",
    tagline: "6×5 · Tumble · Bomben bis ×500",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,5 %",
    badge: "Hot",
    image: "/games/bonbon-regen.jpg",
    family: "pragmatic",
  },
  {
    slug: "goldwolf",
    name: "Goldwolf",
    tagline: "Hold & Win · 6 Münzen · 3 Nachdreher",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,1 %",
    badge: "Neu",
    image: "/games/goldwolf.jpg",
    family: "studio",
  },
  {
    slug: "raubfisch",
    name: "Raubfisch",
    tagline: "Angler sammelt Fische · 10 Freispiele",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,2 %",
    badge: "Hot",
    image: "/games/raubfisch.jpg",
    family: "pragmatic",
  },
  {
    slug: "bienenrausch",
    name: "Bienenrausch",
    tagline: "7×7 Cluster · Tumble ab 5",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,4 %",
    badge: "Neu",
    image: "/games/bienenrausch.jpg",
    family: "studio",
  },
  {
    slug: "sternenblitz",
    name: "Sternenblitz",
    tagline: "Beide Richtungen · Expanding Wild · Nachdrehen",
    kind: "slot",
    volatility: "Niedrig",
    rtp: "96,1 %",
    badge: "Klassiker",
    image: "/games/sternenblitz.jpg",
    family: "studio",
  },
  {
    slug: "huff-und-puff",
    name: "Huff und Puff",
    tagline: "2× Säge · Mini Minor Major Grand",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,2 %",
    badge: "Hot",
    image: "/games/huff-und-puff.jpg",
    family: "studio",
  },
  {
    slug: "pharaos-erbe",
    name: "Pharaos Erbe",
    tagline: "10 Freispiele · Expanding zahlt mit Lücken",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,1 %",
    badge: "Beliebt",
    image: "/games/pharaos-erbe.jpg",
    family: "studio",
  },
  {
    slug: "neon-drift",
    name: "Neon Drift",
    tagline: "243 Wege · Tumble · Multiplikator",
    kind: "slot",
    volatility: "Mittel",
    rtp: "96,5 %",
    badge: "Neu",
    image: "/games/neon-drift.jpg",
    family: "pragmatic",
  },
  {
    slug: "drachenfeuer",
    name: "Drachenfeuer",
    tagline: "Fire Link · Mini Minor Major Grand",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,0 %",
    image: "/games/drachenfeuer.jpg",
    family: "studio",
  },
  {
    slug: "nordlicht",
    name: "Nordlicht",
    tagline: "Frozen Wilds · ×3 im Bonus",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,1 %",
    image: "/games/nordlicht.jpg",
    family: "studio",
  },
  {
    slug: "kirschkoenig",
    name: "Kirschkönig",
    tagline: "Risiko Rot/Schwarz · 2× Kirschen",
    kind: "slot",
    volatility: "Niedrig",
    rtp: "97,0 %",
    image: "/games/kirschkoenig.jpg",
    family: "studio",
  },
  {
    slug: "saphirnacht",
    name: "Saphirnacht",
    tagline: "Tresor · Expanding Gems",
    kind: "slot",
    volatility: "Mittel",
    rtp: "96,4 %",
    image: "/games/saphirnacht.jpg",
    family: "studio",
  },
  {
    slug: "flammenstern",
    name: "Flammenstern",
    tagline: "5 Linien · 2er zählt · Gewinnleiter",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,3 %",
    badge: "Merkur",
    image: "/games/flammenstern.jpg",
    family: "merkur",
  },
  {
    slug: "extra-safe",
    name: "Extra Safe",
    tagline: "Wild ×2 ×3 ×7 · beide Richtungen",
    kind: "slot",
    volatility: "Mittel",
    rtp: "94,3 %",
    badge: "Merkur",
    image: "/games/extra-safe.jpg",
    family: "merkur",
  },
  {
    slug: "zauberspiegel",
    name: "Zauberspiegel",
    tagline: "Expanding zahlt mit Lücken · Risiko",
    kind: "slot",
    volatility: "Hoch",
    rtp: "94,1 %",
    badge: "Merkur",
    image: "/games/zauberspiegel.jpg",
    family: "merkur",
  },
  {
    slug: "multi-wild",
    name: "Multi Wild",
    tagline: "243 Wege · gestapelte Wilds",
    kind: "slot",
    volatility: "Mittel",
    rtp: "96,0 %",
    badge: "Merkur",
    image: "/games/multi-wild.jpg",
    family: "merkur",
  },
  {
    slug: "triple-chance",
    name: "Triple Chance",
    tagline: "3 Walzen · Halten · Leiter",
    kind: "slot",
    volatility: "Niedrig",
    rtp: "97,1 %",
    badge: "Klassiker",
    image: "/games/triple-chance.jpg",
    family: "merkur",
  },
  {
    slug: "heisse-fruechte",
    name: "Heiße Früchte",
    tagline: "5 Linien · 2 Kirschen · 5000× Sieben",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,1 %",
    badge: "Merkur",
    image: "/games/heisse-fruechte.jpg",
    family: "merkur",
  },
  {
    slug: "gluecksklee",
    name: "Glücksklee",
    tagline: "Klee-Wild · 15 Freispiele · Risiko",
    kind: "slot",
    volatility: "Mittel",
    rtp: "95,1 %",
    badge: "Merkur",
    image: "/games/gluecksklee.jpg",
    family: "merkur",
  },
  {
    slug: "immer-heiss",
    name: "Immer Heiß",
    tagline: "5 Linien immer an · Stern bis 5000×",
    kind: "slot",
    volatility: "Hoch",
    rtp: "96,1 %",
    badge: "Merkur",
    image: "/games/immer-heiss.jpg",
    family: "merkur",
  },
  {
    slug: "nur-juwelen",
    name: "Nur Juwelen",
    tagline: "5 Edelsteine · Diamant ab 2 · Leiter",
    kind: "slot",
    volatility: "Mittel",
    rtp: "96,0 %",
    badge: "Merkur",
    image: "/games/nur-juwelen.jpg",
    family: "merkur",
  },
  {
    slug: "plinko",
    name: "Plinko",
    tagline: "12 Peg-Reihen · mehrere Bälle",
    kind: "original",
    volatility: "Mittel",
    rtp: "96,6 %",
    badge: "Original",
    image: "/games/plinko.jpg",
    family: "studio",
  },
  {
    slug: "minen",
    name: "Minen",
    tagline: "5×5 · Cashout",
    kind: "original",
    volatility: "Hoch",
    rtp: "97,0 %",
    badge: "Original",
    image: "/games/minen.jpg",
    family: "studio",
  },
  {
    slug: "lift",
    name: "Lift",
    tagline: "Multiplier · Cashout vor dem Crash",
    kind: "original",
    volatility: "Hoch",
    rtp: "97,0 %",
    badge: "Original",
    image: "/games/lift.jpg",
    family: "studio",
  },
  {
    slug: "gluecksrad",
    name: "Glücksrad",
    tagline: "Live Show · bis 40× · Bonusfelder",
    kind: "original",
    volatility: "Hoch",
    rtp: "96,0 %",
    badge: "Live",
    image: "/games/gluecksrad.jpg",
    family: "live",
  },
  {
    slug: "keno",
    name: "Keno",
    tagline: "80 Zahlen · 20 Kugeln",
    kind: "original",
    volatility: "Mittel",
    rtp: "96,4 %",
    image: "/games/keno.jpg",
    family: "studio",
  },
  {
    slug: "wuerfel",
    name: "Würfel",
    tagline: "Über / Unter · 99 % Auszahlung",
    kind: "original",
    volatility: "Mittel",
    rtp: "99,0 %",
    badge: "Original",
    image: "/games/wuerfel.jpg",
    family: "studio",
  },
  {
    slug: "hi-lo",
    name: "Hi-Lo",
    tagline: "Höher oder niedriger · steigende Multiplikatoren",
    kind: "original",
    volatility: "Mittel",
    rtp: "99,0 %",
    badge: "Neu",
    image: "/games/card-back-red.jpg",
    family: "studio",
  },
  {
    slug: "schwelle",
    name: "Schwelle",
    tagline: "Ziel-Multi · sofort",
    kind: "original",
    volatility: "Hoch",
    rtp: "99,0 %",
    badge: "Original",
    image: "/games/schwelle.jpg",
    family: "studio",
  },
  {
    slug: "rubbellos",
    name: "Rubbellos",
    tagline: "3 gleiche Felder · Instant",
    kind: "original",
    volatility: "Hoch",
    rtp: "96,5 %",
    badge: "Neu",
    image: "/games/rubbellos.jpg",
    family: "studio",
  },
  {
    slug: "drache-tiger",
    name: "Drache & Tiger",
    tagline: "Eine Karte · 8:1 Unentschieden",
    kind: "table",
    table: "baccarat",
    volatility: "Niedrig",
    rtp: "96,3 %",
    badge: "Live",
    image: "/games/drache-tiger.jpg",
    family: "live",
  },
  {
    slug: "blitz-roulette",
    name: "Blitz-Roulette",
    tagline: "Lucky Numbers bis 500×",
    kind: "table",
    table: "roulette",
    volatility: "Hoch",
    rtp: "95,8 %",
    badge: "Live",
    image: "/games/blitz-roulette.jpg",
    family: "live",
  },
  {
    slug: "blackjack",
    name: "Blackjack",
    tagline: "6 Decks · 3:2 · Europäisch",
    kind: "table",
    table: "blackjack",
    volatility: "Niedrig",
    rtp: "99,4 %",
    badge: "Klassiker",
    image: "/games/blackjack.jpg",
  },
  {
    slug: "roulette",
    name: "Roulette",
    tagline: "Europäisch · Einzel-Null",
    kind: "table",
    table: "roulette",
    volatility: "Mittel",
    rtp: "97,3 %",
    image: "/games/roulette.jpg",
  },
  {
    slug: "baccarat",
    name: "Baccarat",
    tagline: "Punto Banco · Commission",
    kind: "table",
    table: "baccarat",
    volatility: "Niedrig",
    rtp: "98,9 %",
    image: "/games/baccarat.jpg",
  },
];

export function gameBySlug(slug: string): GameInfo | undefined {
  return GAMES.find((g) => g.slug === slug);
}

export const DEPOSIT_PRESETS = [1000, 2000, 5000, 10000, 25000, 50000, 100000] as const;

export const PAYMENT_METHODS = [
  { id: "visa", label: "Visa", kind: "card" },
  { id: "mastercard", label: "Mastercard", kind: "card" },
  { id: "paypal", label: "PayPal", kind: "wallet" },
  { id: "klarna", label: "Klarna", kind: "wallet" },
  { id: "sofort", label: "Sofort", kind: "wallet" },
  { id: "applepay", label: "Apple Pay", kind: "wallet" },
  { id: "crypto", label: "Krypto", kind: "crypto" },
] as const;

export type PaymentMethodId = (typeof PAYMENT_METHODS)[number]["id"];
